//! Core helper types shared by the `gpui-form` workspace.

pub mod component_suffix;
pub mod numeric;
pub mod path;
#[cfg(feature = "phone")]
pub mod phone;
pub mod state;

pub use path::FieldPath;
pub use state::FormState;

/// Shared contract for typed component-field enums generated by
/// `#[derive(GpuiForm)]`.
pub trait FormField: Copy + Eq + Ord {
    /// Source-level Rust field name represented by this variant.
    fn name(self) -> &'static str;
}
