//! InfiniteSelect - A cascading select component for infinite select enums
//!
//! This module provides support for enums where variants contain inner values,
//! creating a master-slave relationship between selects. Supports infinite nesting depth
//! with heterogeneous inner types (each variant can have a different inner type).
//!
//! # Example
//!
//! Both tuple-style and struct-style variants are supported:
//!
//! ```ignore
//! // Tuple-style variants
//! #[derive(Clone, Debug, Default, InfiniteSelect)]
//! enum Country {
//!     #[default]
//!     USA(USAState),
//!     Canada(CanadaProvince),
//!     Germany(GermanyState),
//! }
//!
//! // Struct-style variants
//! #[derive(Clone, Debug, Default, InfiniteSelect)]
//! enum Country {
//!     #[default]
//!     USA { state: USAState },
//!     Canada { province: CanadaProvince },
//!     Germany { state: GermanyState },
//! }
//!
//! #[derive(Clone, Debug, Default, InfiniteSelect)]
//! enum USAState {
//!     #[default]
//!     California(CaliforniaCity),
//!     Texas(TexasCity),
//!     NewYork(NewYorkCity),
//! }
//!
//! #[derive(Clone, Debug, Default, InfiniteSelect)]
//! enum CaliforniaCity {
//!     #[default]
//!     LosAngeles,
//!     SanFrancisco,
//!     SanDiego,
//! }
//! ```
//!
//! This creates a hierarchy: Country -> State -> City with automatic cascading.
//! When the user selects a Country, the State select updates. When they select
//! a State, the City select updates.
//!
//! Note: Each variant can have a *different* inner type. This is supported through
//! dynamic dispatch at runtime.

use gpui::SharedString;
use gpui_component::select::SelectItem;

/// Trait for infinite select enums that expose their inner type.
///
/// This trait is derived using `#[derive(InfiniteSelect)]` and provides:
/// - The variant list at each level.
/// - Child variant names for cascading selects.
/// - Index-based child selection to update nested values.
///
/// Unlike a simple associated type approach, this trait supports heterogeneous
/// inner types: each variant can contain a different inner type.
///
/// Implementation notes:
/// - Indices are based on the order of `variants()` at each level.
/// - `child_variant_names()` and `set_child_by_index()` must use the same ordering.
/// - `set_child_by_path()` should apply indices recursively in that same order.
///
/// The derive macro generated by gpui-form-component-derive satisfies these
/// requirements.
pub trait InfiniteSelect: Sized + Clone + Default + 'static {
    /// Returns all possible variants at this level (with default inner values).
    fn variants() -> Vec<Self>;

    /// Returns the variant name/discriminant as a string.
    fn variant_name(&self) -> &'static str;

    /// Returns true if this variant contains an inner value.
    fn has_inner(&self) -> bool;

    /// Returns the variant names of the children for this specific variant.
    /// Returns an empty vec for unit variants or variants without children.
    fn child_variant_names(&self) -> Vec<&'static str>;

    /// Creates a new instance with the child at the given index.
    /// Returns None if the variant doesn't have children or index is out of bounds.
    fn set_child_by_index(&self, index: usize) -> Option<Self>;

    /// Sets the child at a given path depth recursively.
    /// `path` is a slice of indices, where path[0] is the child index at this level,
    /// path[1] is the grandchild index, etc.
    /// Returns None if any index is out of bounds or the path is empty.
    fn set_child_by_path(&self, path: &[usize]) -> Option<Self>;

    /// Returns the depth of nesting for this variant's children.
    /// Returns 0 for leaf variants.
    fn child_depth(&self) -> usize;

    /// Returns the maximum depth of nesting for this enum type.
    fn depth() -> usize;

    /// Returns the variant names of the inner value's children.
    /// This goes one level deeper than child_variant_names().
    /// For Country::USA(California(...)), this returns the cities in California.
    fn inner_child_variant_names(&self) -> Vec<&'static str>;

    /// Sets a child on the inner value and wraps it back.
    /// For Country::USA(California), calling this with index 1 would return
    /// Country::USA(Texas) if Texas is at index 1.
    fn inner_set_child_by_index(&self, index: usize) -> Option<Self>;

    /// Returns true if the inner value itself has children.
    fn inner_has_inner(&self) -> bool;

    /// Returns the localized label for this type (level).
    fn type_label(&self) -> SharedString;

    /// Returns the localized description for this type (level).
    fn type_description(&self) -> SharedString;

    /// Returns the localized label for the child at the given depth relative to this node.
    /// depth 0 = immediate child.
    fn child_label_at_depth(&self, depth: usize) -> Option<SharedString>;

    /// Returns the localized description for the child at the given depth.
    fn child_description_at_depth(&self, depth: usize) -> Option<SharedString>;

    /// Internal method to delegate label lookup to inner value
    fn inner_child_label_at_depth(&self, depth: usize) -> Option<SharedString>;

    /// Internal method to delegate description lookup to inner value
    fn inner_child_description_at_depth(&self, depth: usize) -> Option<SharedString>;
}

/// A wrapper for infinite select enum variants that implements `SelectItem`.
///
/// This allows infinite select enum variants to be displayed in a select dropdown
/// while preserving access to their inner values.
#[derive(Clone)]
pub struct InfiniteSelectItem<T: InfiniteSelect> {
    value: T,
    title: SharedString,
}

impl<T: InfiniteSelect> InfiniteSelectItem<T> {
    /// Create a new InfiniteSelectItem with a custom title.
    ///
    /// This is useful when you want to display localized or user-facing labels
    /// instead of the raw variant name.
    pub fn new(value: T, title: impl Into<SharedString>) -> Self {
        Self {
            value,
            title: title.into(),
        }
    }

    /// Create an InfiniteSelectItem using the variant name as the title.
    pub fn from_variant(value: T) -> Self {
        let title = value.variant_name();
        Self {
            value,
            title: title.into(),
        }
    }

    /// Get a reference to the inner value.
    pub fn get_value(&self) -> &T {
        &self.value
    }

    /// Consume self and return the inner value.
    pub fn into_value(self) -> T {
        self.value
    }

    /// Check if this variant has nested inner values.
    pub fn has_inner(&self) -> bool {
        self.value.has_inner()
    }

    /// Get the child variant names if this variant has children.
    pub fn child_variant_names(&self) -> Vec<&'static str> {
        self.value.child_variant_names()
    }

    /// Set the child by index and return a new item.
    pub fn with_child_at(&self, index: usize) -> Option<Self> {
        self.value.set_child_by_index(index).map(Self::from_variant)
    }
}

impl<T: InfiniteSelect> SelectItem for InfiniteSelectItem<T> {
    type Value = T;

    fn title(&self) -> SharedString {
        self.title.clone()
    }

    fn value(&self) -> &Self::Value {
        &self.value
    }
}

/// Helper function to create select items from infinite select enum variants.
///
/// Items are created in the same order as `T::variants()` and use
/// `InfiniteSelectItem::from_variant`, which sets titles from `variant_name()`.
pub fn to_select_items<T>() -> Vec<InfiniteSelectItem<T>>
where
    T: InfiniteSelect,
{
    T::variants()
        .into_iter()
        .map(InfiniteSelectItem::from_variant)
        .collect()
}

/// Represents a selection path through nested infinite select enums.
///
/// Each element is the index of the selected variant at that depth level.
/// Indices are based on the ordering of `variants()` for the enum at that level.
#[derive(Clone, Debug, Default)]
pub struct InfiniteSelectPath {
    indices: Vec<usize>,
}

impl InfiniteSelectPath {
    /// Create a new empty selection path.
    pub fn new() -> Self {
        Self {
            indices: Vec::new(),
        }
    }

    /// Create a path with the given indices.
    pub fn with_indices(indices: Vec<usize>) -> Self {
        Self { indices }
    }

    /// Get the selection index at a given depth.
    pub fn get(&self, depth: usize) -> Option<usize> {
        self.indices.get(depth).copied()
    }

    /// Set the selection at a given depth, truncating any deeper selections.
    ///
    /// This keeps the path contiguous (no gaps) and ensures deeper selections
    /// always correspond to the currently selected parent.
    pub fn set(&mut self, depth: usize, index: usize) {
        self.indices.truncate(depth);
        self.indices.push(index);
    }

    /// Clear selections from a given depth onwards.
    pub fn clear_from(&mut self, depth: usize) {
        self.indices.truncate(depth);
    }

    /// Truncate the path to the given length.
    pub fn truncate(&mut self, len: usize) {
        self.indices.truncate(len);
    }

    /// Get the current depth of the selection.
    pub fn len(&self) -> usize {
        self.indices.len()
    }

    /// Get all indices as a slice.
    pub fn indices(&self) -> &[usize] {
        &self.indices
    }

    /// Check if the path is empty.
    pub fn is_empty(&self) -> bool {
        self.indices.is_empty()
    }
}

/// Build a value from a selection path.
///
/// This recursively constructs the nested enum by following the path
/// and setting children at each level.
///
/// Returns `None` if the path is empty or any index is out of range.
///
/// The path indices work as follows:
/// - path[0]: selects the variant at the root level
/// - path[1]: selects the child variant within the root's inner value
/// - path[2]: selects the grandchild variant, etc.
///
/// # Example
/// ```ignore
/// // Build Country::USA(USAState::Texas(TexasCity::Austin))
/// let mut path = InfiniteSelectPath::new();
/// path.set(0, 0); // USA (index 0)
/// path.set(1, 1); // Texas (index 1 within USAState)
/// path.set(2, 2); // Austin (index 2 within TexasCity)
/// let country: Country = build_from_path(&path).unwrap();
/// ```
pub fn build_from_path<T: InfiniteSelect>(path: &InfiniteSelectPath) -> Option<T> {
    if path.is_empty() {
        return None;
    }

    let variants = T::variants();
    let root_index = path.get(0)?;
    let root = variants.get(root_index)?.clone();

    // If there are more levels in the path, use set_child_by_path
    if path.len() > 1 {
        root.set_child_by_path(&path.indices()[1..])
    } else {
        Some(root)
    }
}
