//! Generator for the per-form typed path type (`<Name>FormPath`).
//!
//! Backlog feature #8 ("Typed field paths and field IDs", FLAT v1) emits a
//! strongly-typed newtype wrapper around [`::gpui_form::core::FieldPath`] for
//! every `#[derive(GpuiForm)]` form, so validation, dirty tracking, focus,
//! analytics, and schema export share ONE typed way to name fields instead of
//! ad-hoc strings.
//!
//! # Scope
//!
//! This generator ships **FLAT v1 only**: each constructor names a single
//! field. Typed nested-path and list-item-path constructors arrive with
//! backlog features #2 ("Nested forms") and #3 ("Repeated fields").
//! Hand-built multi-segment paths via
//! [`FieldPath::new(&["a", "b"])`](::gpui_form::core::FieldPath::new) work
//! today; typed composition of paths is later.
//!
//! # Rules
//!
//! - `<Name>FormPath` carries **no generics**, even for generic source
//!   structs, because a path only names fields — it stores no typed values.
//! - Skipped fields are EXCLUDED from the constructors (they are absent from
//!   the value holder too).
//! - If a form has zero non-skipped fields, the type is still emitted with
//!   `new()` / `path()` / `into_path()` and no per-field constructors.
//! - The generated code reaches the shared primitive via the facade path
//!   `::gpui_form::core::FieldPath`, mirroring how `value_holder.rs` reaches
//!   `::gpui_form::bon`.
//! - `FieldPath` is a headless primitive (no GPUI, no serde). It is NOT behind
//!   a feature flag, so this generator emits NO `#[cfg(...)]` attrs and NO
//!   serde derives.

use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use syn::DeriveInput;

use crate::derives::gpui_form::structs::FieldOptionality;

/// Generates the `<Name>FormPath` newtype plus its impls for a single form.
///
/// The returned tokens are spliced into the final derive output next to the
/// value-holder tokens. They always emit a path type — even for a form with
/// zero non-skipped fields — per the feature #8 contract.
pub fn generate_field_path(original_input: &DeriveInput, fields: &[FieldOptionality]) -> TokenStream {
    let form_path_ident = format_ident!("{}FormPath", original_input.ident);

    // One freestanding `pub fn <field>() -> Self` constructor per non-skipped
    // field. Named identically to the field, callable as
    // `<Name>FormPath::<field>()`. `stringify!` yields the field ident as a
    // `&'static str`, matching the call shape `FieldPath::new(&[&'static str])`.
    let constructors: Vec<TokenStream> = fields
        .iter()
        .filter(|f| !f.skip)
        .map(|f| {
            let field_name = &f.field_name;
            quote! {
                /// Build a path naming this field.
                pub fn #field_name() -> Self {
                    Self(::gpui_form::core::FieldPath::new(&[stringify!(#field_name)]))
                }
            }
        })
        .collect();

    quote! {
        /// Typed path to a field on this form.
        ///
        /// Generated by `#[derive(GpuiForm)]` as backlog feature #8 (FLAT v1).
        /// Each constructor names a single non-skipped field. Typed nested and
        /// list-item paths arrive with backlog features #2 and #3.
        #[derive(Clone, Debug, Eq, PartialEq, ::core::hash::Hash)]
        pub struct #form_path_ident(::gpui_form::core::FieldPath);

        impl #form_path_ident {
            /// Build a path from an explicit slice of static segments.
            ///
            /// Mirrors [`::gpui_form::core::FieldPath::new`]; useful for
            /// hand-built multi-segment paths until typed nested/list
            /// constructors land with features #2/#3.
            pub fn new(segments: &[&'static str]) -> Self {
                Self(::gpui_form::core::FieldPath::new(segments))
            }

            #(#constructors)*

            /// Borrow the underlying shared [`::gpui_form::core::FieldPath`].
            pub fn path(&self) -> &::gpui_form::core::FieldPath {
                &self.0
            }

            /// Consume this typed path and return the underlying shared
            /// [`::gpui_form::core::FieldPath`].
            pub fn into_path(self) -> ::gpui_form::core::FieldPath {
                self.0
            }
        }

        impl ::core::fmt::Display for #form_path_ident {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                ::core::fmt::Display::fmt(&self.0, f)
            }
        }

        impl ::core::convert::AsRef<::gpui_form::core::FieldPath> for #form_path_ident {
            fn as_ref(&self) -> &::gpui_form::core::FieldPath {
                &self.0
            }
        }

        impl ::core::ops::Deref for #form_path_ident {
            type Target = ::gpui_form::core::FieldPath;
            fn deref(&self) -> &Self::Target {
                &self.0
            }
        }
    }
}
