[package]
name = "some-lib-forms"
version = "0.1.0"
edition.workspace = true
license = "Unlicense"
publish = false


[dependencies]
anyhow = { workspace = true }
gpui = { workspace = true }
gpui-component = { workspace = true }
gpui-form = { features = [ "phone" ], workspace = true }
gpui-form-i18n = { features = [ "component" ], workspace = true }
gpui-storybook = { features = [ "macros" ], workspace = true }
gpui-storybook-core = { workspace = true }
gpui_platform = { workspace = true }
rust-i18n = { workspace = true }
rust_decimal = { workspace = true }
some-lib = { path = "../some-lib" }
strum = { workspace = true }
unic-langid = { workspace = true }
